# Generated by Django 3.1.4 on 2021-01-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('process', models.CharField(max_length=200, unique=True, verbose_name='処理')),
                ('calc', models.CharField(max_length=200, unique=True, verbose_name='演算')),
                ('data1_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='データ１')),
                ('data1_col', models.CharField(blank=True, max_length=200, null=True, verbose_name='データ１列')),
                ('data2_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='データ２')),
                ('data2_col', models.CharField(blank=True, max_length=200, null=True, verbose_name='データ２列')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '処理・加工',
                'verbose_name_plural': '処理・加工',
            },
        ),
    ]
