# Generated by Django 3.1.4 on 2021-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='calc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='演算'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data1_col',
            field=models.CharField(default='default', max_length=200, verbose_name='データ１列'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data1_name',
            field=models.CharField(default='default', max_length=200, verbose_name='データ１'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='処理'),
        ),
    ]
