# Generated by Django 3.1.4 on 2021-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20210117_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='data1_col',
            field=models.CharField(max_length=200, verbose_name='データ１列'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data1_name',
            field=models.CharField(max_length=200, verbose_name='データ１'),
        ),
    ]
