# Generated by Django 3.1.4 on 2021-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20210114_2207'),
        ('process', '0004_auto_20210118_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='data1_name',
            field=models.ManyToManyField(default='default', to='graph.CSVColumn', verbose_name='データ１'),
        ),
    ]
