# Generated by Django 3.1.4 on 2021-01-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20210114_2207'),
        ('process', '0007_auto_20210119_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='data1_col',
        ),
        migrations.AddField(
            model_name='process',
            name='data1_col',
            field=models.ManyToManyField(related_name='data1_col', to='graph.CSVColumn', verbose_name='データ１'),
        ),
        migrations.RemoveField(
            model_name='process',
            name='data2_col',
        ),
        migrations.AddField(
            model_name='process',
            name='data2_col',
            field=models.ManyToManyField(related_name='data2_col', to='graph.CSVColumn', verbose_name='データ２'),
        ),
    ]
