# Generated by Django 3.1.4 on 2021-01-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20210119_2356'),
        ('process', '0010_auto_20210119_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='calc',
            field=models.CharField(blank=True, choices=[], max_length=200, null=True, verbose_name='データ１、２の演算'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data1_col',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data1_col', to='graph.csvcolumn', verbose_name='データ１'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data2_col',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data2_col', to='graph.csvcolumn', verbose_name='データ２'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(blank=True, choices=[('wd', '曜日ごと'), ('7d', '７日平均')], max_length=2, null=True, verbose_name='曜日ごと、７日平均'),
        ),
    ]
