# Generated by Django 3.1.4 on 2021-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_auto_20210123_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='曜日ごと、７日平均'),
        ),
    ]
