# Generated by Django 3.1.4 on 2021-01-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_auto_20210123_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(blank=True, choices=[('wd', '曜日ごと'), ('7d', '７日平均')], max_length=16, null=True, verbose_name='曜日ごと、７日平均'),
        ),
    ]
