# Generated by Django 3.1.4 on 2021-01-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_auto_20210123_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='７日平均',
            new_name='sevendays',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='曜日ごと',
            new_name='weekday',
        ),
    ]
