# Generated by Django 3.1.4 on 2021-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0016_auto_20210123_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='calc',
            field=models.CharField(blank=True, choices=[('dot', 'データ１ × データ２')], default='', max_length=100, null=True, verbose_name='データ１、２の演算'),
        ),
    ]
