# Generated by Django 3.1.4 on 2021-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0018_auto_20210126_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='weekday',
            field=models.BooleanField(default=False, verbose_name='曜日ごと(移動平均無効)'),
        ),
    ]
