# Generated by Django 3.1.4 on 2021-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_auto_20210129_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='data2_shift',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='単純移動平均'),
        ),
    ]
