# Generated by Django 3.1.4 on 2021-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0021_auto_20210202_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='data2_shift',
        ),
        migrations.AddField(
            model_name='process',
            name='data1_periods',
            field=models.SmallIntegerField(default=0, verbose_name='データ１の処理間隔'),
        ),
        migrations.AddField(
            model_name='process',
            name='data1_process',
            field=models.CharField(blank=True, choices=[('shift', '累計 → 差分'), ('pct_change', '変化率')], default='', max_length=100, null=True, verbose_name='データ１の処理'),
        ),
        migrations.AddField(
            model_name='process',
            name='data2_periods',
            field=models.SmallIntegerField(default=0, verbose_name='データ２の処理間隔'),
        ),
        migrations.AddField(
            model_name='process',
            name='data2_process',
            field=models.CharField(blank=True, choices=[('shift', '累計 → 差分'), ('pct_change', '変化率')], default='', max_length=100, null=True, verbose_name='データ２の処理'),
        ),
    ]
