# Generated by Django 3.1.4 on 2021-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0022_auto_20210202_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='calc',
            field=models.CharField(choices=[('1-axis', 'なし（１軸）'), ('2-axis', 'なし（２軸）'), ('add', 'たし算： データ１ + データ２'), ('sub', 'ひき算： データ１ − データ２'), ('mul', 'かけ算： データ１ × データ２'), ('div', 'わり算： データ１ ÷ データ２')], default='1-axis', max_length=100, verbose_name='データ１、２の演算'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data1_process',
            field=models.CharField(blank=True, choices=[('shift', '差分'), ('pct_change', '変化率')], default='', max_length=100, null=True, verbose_name='データ１の処理'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data2_process',
            field=models.CharField(blank=True, choices=[('shift', '差分'), ('pct_change', '変化率')], default='', max_length=100, null=True, verbose_name='データ２の処理'),
        ),
    ]
