# Generated by Django 3.1.4 on 2021-02-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0023_auto_20210213_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='画像URL')),
                ('process', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pimage', to='process.process', verbose_name='対象CSV')),
            ],
            options={
                'verbose_name': '処理・加工_画像',
                'verbose_name_plural': '処理・加工_画像',
            },
        ),
    ]
