# Generated by Django 3.1.4 on 2021-02-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0024_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='process',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='process.process', verbose_name='対象CSV'),
        ),
    ]
