# Generated by Django 3.1.4 on 2021-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0025_auto_20210216_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='画像URL'),
        ),
    ]
