# Generated by Django 3.1.4 on 2021-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0026_auto_20210218_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='data1_process',
            field=models.CharField(blank=True, choices=[('shift', 'X軸シフト'), ('difference', '差分'), ('pct_change', '変化率')], default='', max_length=100, null=True, verbose_name='データ１の処理'),
        ),
        migrations.AlterField(
            model_name='process',
            name='data2_process',
            field=models.CharField(blank=True, choices=[('shift', 'X軸シフト'), ('difference', '差分'), ('pct_change', '変化率')], default='', max_length=100, null=True, verbose_name='データ２の処理'),
        ),
    ]
