# Generated by Django 3.1.4 on 2021-01-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='出典')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('csv', models.FileField(max_length=300, unique=True, upload_to='csv/', verbose_name='CSV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '参照ファイル',
                'verbose_name_plural': '参照ファイル',
            },
        ),
        migrations.CreateModel(
            name='PlotMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('lines', '折れ線グラフ')], default='lines', max_length=100, verbose_name='グラフの種類')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='graph.source', verbose_name='対象CSV')),
            ],
            options={
                'verbose_name': 'グラフの種類',
                'verbose_name_plural': 'グラフの種類',
            },
        ),
        migrations.CreateModel(
            name='CSVColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_col_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='列番号')),
                ('csv_col_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='ラベル')),
                ('df_col_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表示名')),
                ('axis', models.CharField(blank=True, choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1, null=True, verbose_name='軸')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='graph.source', verbose_name='対象CSV')),
            ],
            options={
                'verbose_name': 'CSVからDFへの変換設定',
                'verbose_name_plural': 'CSVからDFへの変換設定',
            },
        ),
    ]
