# Generated by Django 3.1.4 on 2021-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20210114_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvcolumn',
            name='axis',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('Y', 'Y')], max_length=1, null=True, verbose_name='軸'),
        ),
    ]
