# Generated by Django 3.1.4 on 2021-01-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20210129_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='csv_data',
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data', models.TextField(blank=True, null=True, verbose_name='CSVデータ')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='graph.source', verbose_name='対象CSV')),
            ],
            options={
                'verbose_name': 'グラフの種類',
                'verbose_name_plural': 'グラフの種類',
            },
        ),
    ]
