# Generated by Django 3.1.4 on 2021-01-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_auto_20210129_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='csv_data',
            new_name='csv_str',
        ),
    ]
