# Generated by Django 3.1.4 on 2021-02-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_auto_20210130_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvdata',
            options={'verbose_name': 'CSVデータ', 'verbose_name_plural': 'CSVデータ'},
        ),
    ]
