# Generated by Django 3.1.4 on 2021-02-13 08:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_auto_20210202_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
