# Generated by Django 3.1.4 on 2021-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_auto_20210213_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image'),
        ),
    ]
