# Generated by Django 3.1.4 on 2021-02-14 11:21

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_auto_20210214_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='graph.source', verbose_name='対象CSV'),
        ),
        migrations.AlterField(
            model_name='source',
            name='csv',
            field=cloudinary.models.CloudinaryField(max_length=255, unique=True, verbose_name='CSV'),
        ),
    ]
