# Generated by Django 3.1.4 on 2021-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0013_auto_20210214_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='画像URL'),
        ),
    ]
