# Generated by Django 3.1.4 on 2021-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0014_auto_20210214_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='csv',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CSV'),
        ),
    ]
