# Generated by Django 3.1.4 on 2021-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0016_auto_20210218_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='画像URL'),
        ),
    ]
